version: '3.4'

services:
  apirest:
    image: apirest
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
